azure:
  service-bus:
    connection-string: <sensitive_set_get_from_env_var>
endpoints:
  enabled: true
  sensitive: false
info:
  java:
    source: "${java.version}"
logging:
  level:
    root: INFO
management:
  health:
    mongo:
      enabled: true
  info:
    build:
      enabled: true
    git:
      mode: full
server:
  port: 8097
  context-path: /candidate
spring:
  application:
    name: Candidate Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/candidates
---
server:
  port: 8080
spring:
  profiles: kub-aks
